# Generated by Django 4.0.4 on 2022-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='version_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
