# Generated by Django 4.0.4 on 2022-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_testmodel_name_alter_testmodel_version_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='fk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
